spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

restaurant.rabbitmq.queue.orders=restaurant.orders.queue
restaurant.rabbitmq.queue.responses=restaurant.responses.queue
restaurant.rabbitmq.exchange=restaurant.direct
restaurant.rabbitmq.routingkey.orders=restaurant.orders.key
restaurant.rabbitmq.routingkey.responses=restaurant.responses.key