version: '3.8'

services:
    mysql-db:
        image: mysql:8
        container_name: mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laborator
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"

volumes:
    mysql_data:

        
