spring.datasource.url=jdbc:sqlite:books.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
libraryapp.rabbitmq.exchange=libraryapp.direct
libraryapp.rabbitmq.routingkey=libraryapp.routingkey
libraryapp.rabbitmq.queue=libraryapp.queue1